import React from "react"
import { library } from "@fortawesome/fontawesome-svg-core"
import {
  faFacebookF,
  faTwitter,
  faGoogle,
  faYoutube
} from "@fortawesome/free-brands-svg-icons"
import { faCircle } from "@fortawesome/free-regular-svg-icons"
import {
  faChevronRight,
  faChevronLeft,
  faTimes,
  faTimesCircle,
  faPlay,
  faCheck,
  faHandPointer,
  faReply,
  faDollarSign,
  faLock,
  faShareSquare,
  faCheckSquare,
  faUserFriends,
  faShoppingBag,
  faEdit,
  faCamera,
  faMobileAlt,
  faEnvelope,
  faCreditCard,
  faUniversity,
  faCheckCircle,
  faSlidersH,
  faWallet,
  faFileDownload,
  faComments,
  faEllipsisH,
  faBuilding,
  faCalendarAlt,
  faSort

} from "@fortawesome/free-solid-svg-icons"

library.add(
  faChevronRight,
  faChevronLeft,
  faTimes,
  faTimesCircle,
  faPlay,
  faCheck,
  faHandPointer,
  faReply,
  faDollarSign,
  faLock,
  faShareSquare,
  faCheckSquare,
  faUserFriends,
  faShoppingBag,
  faEdit,
  faCamera,
  faMobileAlt,
  faEnvelope,
  faCreditCard,
  faUniversity,
  faCheckCircle,
  faCircle,
  faComments,
  faCalendarAlt,
  faSlidersH,
  faWallet,
  faFileDownload,
  faSort,
  faEllipsisH,
  faBuilding,
  faFacebookF,
  faTwitter,
  faGoogle,
  faYoutube
)
